# Generated by Django 2.0.4 on 2020-03-08 13:08

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '课题组新闻',
                'verbose_name_plural': '课题组新闻',
                'db_table': 'K_news',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='姓名')),
                ('content', models.CharField(max_length=100, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'db_table': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('years', models.CharField(max_length=100, verbose_name='成果时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '研究成果',
                'verbose_name_plural': '研究成果',
                'db_table': 'Results',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='氢安全', max_length=100, verbose_name='作者'),
        ),
    ]
