# Generated by Django 2.0.4 on 2020-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200308_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '氢能资讯', 'verbose_name_plural': '氢能资讯'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '成员介绍', 'verbose_name_plural': '成员介绍'},
        ),
        migrations.AddField(
            model_name='results',
            name='urls',
            field=models.CharField(default='www', max_length=100, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='k_news',
            name='name',
            field=models.CharField(default='氢安全', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='members',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='照片'),
        ),
    ]
