# Generated by Django 2.0.4 on 2020-03-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200308_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='content',
            field=models.CharField(default='请不要超过五百个字符', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='results',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
    ]
