# Generated by Django 2.0.4 on 2020-03-08 14:43

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200308_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mail',
            field=models.CharField(default='请输入邮箱地址', max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='members',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='members',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
