# Generated by Django 2.0.4 on 2020-03-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200308_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='grade',
            field=models.CharField(default='请输入年级（硕士/博士/老师）', max_length=100, verbose_name='年级'),
        ),
    ]
