# Generated by Django 2.0.4 on 2020-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_linktab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='K_news',
        ),
        migrations.DeleteModel(
            name='Linktab',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '我们的轨迹', 'verbose_name_plural': '我们的轨迹'},
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
