# Generated by Django 2.0.4 on 2020-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200312_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default='一个帅比', max_length=100, verbose_name='作者'),
        ),
    ]
