# Generated by Django 2.0.4 on 2020-03-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200312_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
    ]
